name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: build
        uses: actions/checkout@v2
      - run: gcc -c -o stats.o stats.c
      - run: gcc -c -o alert.o alert.c
      - run: g++ -c -o stats-test.o stats-test.cpp
      - run: g++ -Wall -Wextra -o testchecker *.o
      
      - name: run
        run: ./testchecker
