name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
      gcc -c -o stats.o stats.c
      gcc -c -o alert.o alert.c
      g++ -c -o stats-test.o stats-test.cpp
      g++ -Wall -Wextra -o testchecker *.o
      
    - name: run
      run: ./testchecker
